### ISSUE TITLE
标题栏文字没有居中

### ISSUE THREAD

**Issue by littleViolence** [SpikeKing/WclNavigator#2]
"应用标题"的文字没有居中,还是往一边偏着,找不到原因

**Comment by SpikeKing** [comment]
需要重写ActionBar的样式

**Comment by littleViolence** [comment]
原有样式这样:navBarTitleText: {
                    fontSize: 18,
                    color: '#000',
                    textAlign: 'center',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 'bold',
                    flex: 1
                }
如何修改?

**Comment by littleViolence** [comment]
感觉这样写,是会居中的
